---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[oracle-instantclient]
      - recipe[oracle-instantclient::jdbc]
      - recipe[oracle-instantclient::sdk]
      - recipe[oracle-instantclient::sqlplus]
      - recipe[php]
      - recipe[oracle-instantclient::php]
