#!/bin/sh

case "${SSH_ORIGINAL_COMMAND}" in
  *\&*)
    echo "Rejected"
    ;;
  *\(*)
    echo "Rejected"
    ;;
  *\{*)
    echo "Rejected"
    ;;
  *\;*)
    echo "Rejected"
    ;;
  *\<*)
    echo "Rejected"
    ;;
  *\`*)
    echo "Rejected"
    ;;
  *\|*)
    echo "Rejected"
    ;;
  rsync\ --server\ --sender\ -vlogDtprze.iLsf\ .\ /db/mysql/repstaging/*)
    ${SSH_ORIGINAL_COMMAND}
    ;;
  rsync\ --server\ --sender\ -vlogDtprze.iLsf\ .\ /db/instances/prod/data/repstaging/*)
    ${SSH_ORIGINAL_COMMAND}
    ;;
  *)
    echo "Rejected"
    ;;
esac 
